#!/usr/bin/python3

from rich.table import Column, Table
import hashlib
import os
from PIL import Image
import numpy as np
import cv2
from pathlib import Path
from typing import Literal
import json as json_

from toolbox.logger import console
from toolbox.utils import is_image, multi_file_arg, new_path_cleanup
from toolbox.subcommands import cli


Pixels = np.ndarray[tuple[int, ...]]
Indices = np.ndarray[tuple[int, ...]]

META_KEY = "pixel-scramble"

# Mean diff threshold to determine when an image is scrambled.
DIFF_THRESHOLD = 50.0

# Output formats supported.
OUT_FORMATS = ["PNG", "JPEG"]


class ScrambleKey:
    """The scramble key converts a password into a seemingly randomized list of indices used to
    re-order 2d arrays.
    """

    size = 128

    def __init__(self, key_data: bytes | str) -> None:
        if isinstance(key_data, str):
            key_data = key_data.encode("utf8")
        self._bytes = [i & 0xFF for i in hashlib.sha256(key_data).digest()]  # 32 bytes
        self.init()

    def init(self) -> None:
        """
        Initialize a 2d array of indices from a sequence generated by the key bytes
        Scramble the 2d array of indices to create a randomized list of max_length ** 2 indices
        """
        self._sequence = self._get_sequence()  # randomized list if indices
        self._arr = np.arange(self.size**2).reshape(
            (self.size, self.size)
        )  # sequential matrix
        self._arr = do_mod(self._arr, self._sequence)  # scrambled matrix

    def _get_sequence(self) -> Indices:
        """
        Randomize a sequential list of indices based on the key bytes
        We can generate any length array based on the limited number of bytes in the key
        """

        out: list[np.uint32] = []
        arr: list[np.uint32] = list(np.arange(self.size, dtype=np.uint32))

        for rot in range(0, 8, 2):
            for b in self._bytes:
                idx = self._bit_rot(b, rot) % len(arr)
                out.append(arr.pop(idx))

        return np.array(out)

    @staticmethod
    def _bit_rot(byte: int, shift: int) -> int:
        n1 = byte >> (8 - shift)
        n2 = (byte << shift) & 0xFF
        return n1 | n2

    @property
    def array(self):
        return self._arr.flatten()


def load_image(filename: Path | str) -> Pixels:
    img = Image.open(str(filename))
    return np.array(img)


def save_image(arr: np.ndarray, filename: Path | str, fmt: Literal["PNG", "JPEG"]="PNG") -> None:
    """Save the pixel array to a file.
    """
    data = Image.fromarray(arr)
    data.save(str(filename), format=fmt)
    console.log(f"Saved [green]{filename}[/green]")


def do_mod(pixel_array: np.ndarray, key: np.ndarray, do_scramble: bool=True):

    def rotate_cw(array: np.ndarray) -> np.ndarray:
        return np.rot90(array, k=3)

    def rotate_ccw(array: np.ndarray) -> np.ndarray:
        return np.rot90(array, k=1)

    def slant(array: np.ndarray) -> np.ndarray:
        # width / height to determine the ratio for slanting evenly
        diff = float(array.shape[1]) / array.shape[0]
        incr = 0
        for i, row in enumerate(array):
            roll = int(-incr if do_scramble else incr)
            array[i] = np.roll(row, roll, 0)
            incr += diff
        return array

    def scramble(array: np.ndarray):
        if do_scramble:
            return array[key[key < array.shape[0]]]
        
        out = np.copy(array)
        for i, out_index in enumerate(key[key < array.shape[0]]):
            out[out_index] = array[i]
        return out

    processes = [
        scramble,
        slant,
        scramble,
        rotate_cw,
        scramble,
        slant,
        scramble,
        rotate_ccw,
        scramble,
        slant,
        scramble,
    ]

    for process in processes:
        pixel_array = process(pixel_array)

    return pixel_array


@cli.register("image", "metadata", positional="file_paths", ignores=["kwargs"])
def show_meta(file_paths: list[str], json: bool=False, **kwargs):
    """Show image metadata.

    Args:
        file_paths (list[str]): a list of files to read metadata from
        json (bool, optional): output JSON formatted data, default: false
    """
    image_paths = list(filter(is_image, multi_file_arg(*file_paths)))
    for filename in image_paths:
        image = Image.open(filename)
        if json:
            print(json_.dumps(image.info))
            continue
        
        if image.info and len(image.info.items()) > 0:
            table = Table(
                Column("Key", style="white"),
                Column("Value", style="cyan", width=50),
                title=f"[cyan]Metadata[/] for [green]{filename}[/]",
                border_style="#444444",
            )
            for key, val in image.info.items():
                table.add_row(str(key), str(val))
            console.print(table)
        else:
            console.log(f"{filename} has no metadata")
            
            
def is_scrambled(path: Path | str):
    img = cv2.imread(str(path), cv2.IMREAD_GRAYSCALE)
    if img is None:
        return False, -1.0
    
    diff_h = np.abs(img[:, :-1].astype(np.int16) - img[:, 1:].astype(np.int16))
    diff_v = np.abs(img[:-1, :].astype(np.int16) - img[1:, :].astype(np.int16))
    mean_diff = (np.mean(diff_h) + np.mean(diff_v))
    scrambled = (mean_diff > DIFF_THRESHOLD).all()
    
    # console.log(f"Mean difference: {mean_diff} for {path} scrambled={scrambled}")
    
    return scrambled, mean_diff

            
def check_scrambled(file_paths: list[Path]):
    table = Table("Path", "Scrambled", "Mean Diff", border_style="#444444")
    
    for img in list(filter(is_image, multi_file_arg(*file_paths))):
        scrambled, diff = is_scrambled(img)
        clr = "green" if scrambled else "#444444"
        table.add_row(str(img), f"[{clr}]{'scrambled' if scrambled else 'not scrambled'}[/]", f"{diff:.2f} / {DIFF_THRESHOLD:.2f}")
        
    console.print(table)


@cli.register("image", "scramble", positional="file_paths")
def scramble(
    file_paths: list[Path | str],
    unscramble: bool=False,
    password: str="",
    out_dir: Path | str | None=None,
    out_format: Literal["PNG", "JPEG"]="PNG",
    recursive: bool=False,
    remove_existing: bool=False,
    check_only: bool=False,
    multi: bool=False,
) -> None:
    """Scramble the pixels of an image with a password.
    
    Args:
        file_paths (list[str]): Paths to image files, or a folder containing image files
        password (str): Password to use for scrambling, default: ""
        unscramble (bool): If specified, unscramble the image(s), default: false
        out_dir (str): Output directory to save the images to, default: (current directory)
        out_format (str): Output format to use (PNG or JPEG), it is recommended to use PNG, as storing scrambled images in JPEG will result in severe compression artifacts, default: PNG
        recursive (bool): Recursively search the path if a directory is specified, default: false
        remove_existing (bool): If specified, existing files will be removed once scrambled, default: false
        check_only (bool): If specified, only show image scramble status and exit, default: false
        multi (bool): If specified, allow images to be scrambled multiple times, default: false
    """
    assert out_format in OUT_FORMATS, f"Invalid output format {out_format}, use one of {', '.join(OUT_FORMATS)}"
    
    image_paths = list(filter(is_image, multi_file_arg(*file_paths, recursive=recursive)))
    
    assert image_paths, "No images found"
    
    if check_only:
        check_scrambled(image_paths)
        return
    
    key = ScrambleKey(password or b"").array
    op = "Scrambling" if not unscramble else "Unscrambling"
    new_ext = "jpg" if out_format == "JPEG" else "png"
    
    with console.status(op) as status:
        for p in image_paths:
            scrambled, _ = is_scrambled(p)
            if not multi:
                if scrambled and not unscramble:
                    console.log(f"Skipping {p}")
                    continue
                if not scrambled and unscramble:
                    console.log(f"Skipping {p}")
                    continue
            
            status.update(f"{op} [green]{p}[/green]")
            
            initial_arr = load_image(p)
            scrambled_arr = do_mod(initial_arr, key, do_scramble=not unscramble)

            out_dir_ = Path(out_dir or p.parent)
            with new_path_cleanup(out_dir_, is_file=False):
                out_name = os.path.splitext(p.name)[0] + f".{new_ext}"
                new_path = Path(out_dir_ / out_name)
                save_image(scrambled_arr, new_path, fmt=out_format)
                
                if remove_existing and p != new_path:
                    p.unlink()
